### ISSUE TITLE
Creating Feed page

### ISSUE THREAD

**Issue by HokageWizza** [Knight-Angel-Organization/KnightAngelBackend#27]
- [x] Ability to follow and unfollow users
- [ ] Ability to create, update & delete posts
- [x] Get all posts or get posts by following(still working on determining this)

Complete following tasks:
1. [x] Move the determineRequestType function to its own page or move it to pictureController & rename it to something else.
2. [x] Add "logged in" validation to all routes that require users to be logged into the service.
3. [x] move imageSchema schema to its own page and reference it in the other needed pages

**Comment by HokageWizza** [comment]
Sources for Social Media API.:
https://www.youtube.com/watch?v=v9c-pWTAgD4
https://youtu.be/ldGl6L4Vktk?si=G_qUn6qfh1DsRBqO

**Comment by bhopkins0** [comment]
Potential requirement of posts:

Time of post
Poster’s username/ID
Post content
Number of likes
Post title (maybe?)
Image support (maybe array of image links)
