### ISSUE TITLE
Form-Data Streamline

### ISSUE THREAD

**Issue by HokageWizza** [Knight-Angel-Organization/KnightAngelBackend#4]
Enhance all routes in backend to use form-data body type within Postman. Still, retain ability to send data using raw and form-urlencoded

**Comment by bhopkins0** [comment]
Current branch for allowing multiple request types:

https://github.com/Knight-Angel-Organization/KnightAngelBackend/tree/form-data-compatibility

On first glance, it seems that Sendgrid is not compatible with form-data. This is a notable restriction but will investigate.
